sheet:
  spreadsheet_id: 11xTqz5xSSFT_9FzgoO3iwn0U-TcKaezTjm62cRq3WQI
  worksheet: Javascript

table: backends

#column di database

mapping:
  connection:
    column: name

defaults:
  id: uuid
  created_at: now
  updated_at: now
  active: true
  is_deployed: true
  type: javascript
  protocol: js
  host: ""
  authentication_type: ""
  authentication_location: ""
  username: ""
  password: ""
  client_id_key: ""
  client_token_key: ""
  client_token_value: ""
  database: ""
  message_id: 0
  chat_id: 0
  ssl_cert: ""
  ssl_key: ""
  protobuf: ""
  verify_ssl: false
  enable_circuit_breaker: false
  cb_max_requests: 0
  cb_interval: 0
  cb_timeout: 0
  cb_minimum_http_code: 0
  proto_location: ""


#Filter daeri sheet

filter:
  column: Is Deployed
  value: Deployed

#column 
unique: [name] 

on_conflict:
  action: ignore
  keys: [name]