sheet:
  spreadsheet_id: 11xTqz5xSSFT_9FzgoO3iwn0U-TcKaezTjm62cRq3WQI
  worksheet: Javascript

table: gateways

mapping:
  connection:
    column: backend_id
    transform: lookup
    lookup:
      table: backends
      from: name
      to: id
  Endpoint Path:
    column: endpoint_id
    transform: lookup
    lookup:
      table: endpoints
      from: path
      to: id
  Exposed Path:
    column: path

defaults:
  id: uuid
  created_at: now
  updated_at: now
  active: true
  is_deployed: true

filter:
  column: status
  value: active

on_conflict:
  action: ignore
  keys: []