sheet:
  spreadsheet_id: 1wvjDFx2NKzHOhSbFxfBJol6n-RETHm700JNG7s5PppY
  worksheet: HTTP

table: backends

#column di database
mapping:
  Connection:
    column: name
  Protocol:
    column: protocol
  Host:
    column: host

defaults:
  id: uuid
  created_at: now
  updated_at: now
  active: true
  is_deployed: true
  type: http
  authentication_type: ""
  authentication_location: ""
  username: ""
  password: ""
  client_id_key: ""
  client_token_key: ""
  client_token_value: ""
  database: ""
  message_id: 0
  chat_id: 0
  ssl_cert: ""
  ssl_key: ""
  protobuf: ""
  verify_ssl: false
  enable_circuit_breaker: false
  cb_max_requests: 0
  cb_interval: 0
  cb_timeout: 0
  cb_minimum_http_code: 0
  proto_location: ""


#Filter daeri sheet
filters:
- column: Is Deployed
  value: Deployed
- column: type
  value: HTTP

#column sheet dengan value unik
unique: [name]

#mencegah ada data yang duplicate di db
on_conflict:
  action: ignore
  keys: [name]