sheet:
  spreadsheet_id: 1wvjDFx2NKzHOhSbFxfBJol6n-RETHm700JNG7s5PppY
  worksheet: Service

table: endpoints

mapping:
  Connection:
    column: backend_id
    transform: lookup
    lookup:
      table: backends
      from: name
      to: id
  Endpoint Path:
    column: path
  Method:
    column: method
  Access:
    column: type
  Allowed Headers:
    column: allowed_headers
  Interceptor:
    column: request_validator_id
    transform: lookup
    lookup:
      table: request_validators
      from: name
      to: id


defaults:
  id: uuid
  created_at: now
  updated_at: now
  active: true
  skip_activity_log: false
  allowed_response_headers: ""
  sql_statement: ""
  javascript: ""
  response: ""
  request_timeout: 0
  rate_limit: 0
  rate_limit_type: second
  enable_cors: false
  allow_origins: ""
  allow_headers: ""
  allow_credentials: false
  expose_headers: ""
  max_age: 0
  allow_private_network: false
  grpc_service: ""
  webhook_url: ""
  request_transformer_id: ""
  log_transformer_id: ""

filters:
- column: Is Deployed
  value: Deployed
- column: type
  value: HTTP

unique: [path]

on_conflict:
  action: ignore
  keys: []