sheet:
  spreadsheet_id: 1wvjDFx2NKzHOhSbFxfBJol6n-RETHm700JNG7s5PppY
  worksheet: HTTP

table: gateways

mapping:
  Connection:
    column: backend_id
    transform: lookup
    lookup:
      table: backends
      from: name
      to: id
  Endpoint Path:
    column: endpoint_id
    transform: lookup
    lookup:
      table: endpoints
      from: path
      to: id
  Exposed Path:
    column: path

defaults:
  id: uuid
  created_at: now
  updated_at: now
  active: true
  is_deployed: false

filters:
- column: Is Deployed
  value: Deployed
- column: type
  value: HTTP

unique: [path]

on_conflict:
  action: ignore
  keys: []