sheet:
  spreadsheet_id: 1wvjDFx2NKzHOhSbFxfBJol6n-RETHm700JNG7s5PppY
  worksheet: Service

table: client_gateways


#column di database
mapping:
  Consumer Name:
    column: client_id
    transform: lookup
    lookup:
      table: clients
      from: name
      to: id
  Exposed Path:
    column: gateway_id
    transform: lookup
    lookup:
      table: gateways
      from: path
      to: id

defaults:
  id: uuid
  created_at: now
  updated_at: now
  active: true

#filter
filters:
  - column: Access
    value: user
  - column: Consumer name
    not_empty: true
  - column: Endpoint Path
    value: /table-call
    not: true
  - column: Is Deployed
    values: [Deployed]


# #column db dengan value unik
# unique: []

# #mencegah ada data yang duplicate di db
# on_conflict:
#   action: ignore
#   keys: []