sheet:
  spreadsheet_id: 11xTqz5xSSFT_9FzgoO3iwn0U-TcKaezTjm62cRq3WQI
  worksheet: migrasi test

table: customer

mapping:
  nama:
    column: name
  umur:
    column: age
  script:
    column: script
  status:
    column: active
    transform: string_to_bool

defaults:
  id: uuid
  timestamp: now

filter:
  column: status
  value: inactive

on_conflict:
  action: ignore
  keys: [name]